### ISSUE TITLE
Working sample sheet

### ISSUE THREAD

**Issue by vasquini** [BeatsonLab-MicrobialGenomics/micropipe#6]
Hi,

I was wondering what a working sample sheet would be. I  have no Illumina files, and I wish to start from the FAST5 input. I added guppy to  the config file and basecalling finishes successfully, but the demultiplexing step is failing to identify the barcodes and keeps failing. I ran guppy_barcoder outside of micropipe and it identified the barcodes.So this means it's something in the sample sheet that is causing the issues.
I ran the pipeline from assembly-only at first. I originally assumed the long_fastq would be the already demultiplexed fastq files when running starting from assembly, but I keep getting errors. The following was the sample sheet I have been using:
barcode_id,sample_id,long_fastq,genome_size
barcode13,barcode13,demux_guppy_fastq/barcode13/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode13,barcode13,demux_guppy_fastq/barcode13/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_1.fastq,5m
barcode14,barcode14,demux_guppy_fastq/barcode14/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode14,barcode14,demux_guppy_fastq/barcode14/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_1.fastq,5m
barcode15,barcode15,demux_guppy_fastq/barcode15/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode15,barcode15,demux_guppy_fastq/barcode15/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_1.fastq,5m
barcode16,barcode16,demux_guppy_fastq/barcode16/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode16,barcode16,demux_guppy_fastq/barcode16/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_1.fastq,5m
barcode16,barcode16,demux_guppy_fastq/barcode16/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_2.fastq,5m
barcode17,barcode17,demux_guppy_fastq/barcode17/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode17,barcode17,demux_guppy_fastq/barcode17/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_1.fastq,5m
barcode20,barcode20,demux_guppy_fastq/barcode20/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode27,barcode27,demux_guppy_fastq/barcode27/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode46,barcode46,demux_guppy_fastq/barcode46/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode55,barcode55,demux_guppy_fastq/barcode55/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode58,barcode58,demux_guppy_fastq/barcode58/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode60,barcode60,demux_guppy_fastq/barcode60/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode64,barcode64,demux_guppy_fastq/barcode64/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode67,barcode67,demux_guppy_fastq/barcode67/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode72,barcode72,demux_guppy_fastq/barcode72/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode79,barcode79,demux_guppy_fastq/barcode79/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m

**Comment by vmurigneu** [comment]
Hi @vasquini 

Can you please share the command line you're using and the error message? 

Yes to run the assembly only, you need to provide already demultiplexed fastq files in the long_fastq column.  
You have repeat barcodes in your samplesheet ie two lines for barcode 13 for instance. It might be causing the error

**Comment by vasquini** [comment]
Ok I created a merged.fastq file for those barcodes that yielded multiple fastq files, and updated the sample sheet accordingly. I ran assembly-only. I keep getting the same error. I used the exact same command for the assembly-only pipeline:
nextflow micropipe/main.nf --samplesheet samplesheet0217.csv --outdir AssemblyTest0222 --skip_illumina

I changed my samplesheet to this:
(base) [suj7@login02 ~]$ cat samplesheet0217.csv
barcode_id,sample_id,long_fastq,genome_size
barcode03,barcode03,demux_guppy_fastq_new/barcode03/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode08,barcode08,demux_guppy_fastq_new/barcode08/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode12,barcode12,demux_guppy_fastq_new/barcode12/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode13,barcode13,demux_guppy_fastq_new/barcode13/merged.fastq,5m
barcode14,barcode14,demux_guppy_fastq_new/barcode14/merged.fastq,5m
barcode15,barcode15,demux_guppy_fastq_new/barcode15/merged.fastq,5m
barcode16,barcode16,demux_guppy_fastq_new/barcode16/merged.fastq,5m
barcode17,barcode17,demux_guppy_fastq_new/barcode17/merged.fastq,5m
barcode20,barcode20,demux_guppy_fastq_new/barcode20/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode21,barcode21,demux_guppy_fastq_new/barcode21/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode26,barcode26,demux_guppy_fastq_new/barcode26/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode27,barcode27,demux_guppy_fastq_new/barcode27/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode31,barcode31,demux_guppy_fastq_new/barcode31/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode37,barcode37,demux_guppy_fastq_new/barcode37/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode38,barcode38,demux_guppy_fastq_new/barcode38/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode40,barcode40,demux_guppy_fastq_new/barcode40/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode41,barcode41,demux_guppy_fastq_new/barcode41/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode46,barcode46,demux_guppy_fastq_new/barcode46/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode48,barcode48,demux_guppy_fastq_new/barcode48/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode49,barcode49,demux_guppy_fastq_new/barcode49/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode50,barcode50,demux_guppy_fastq_new/barcode50/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode55,barcode55,demux_guppy_fastq_new/barcode55/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode58,barcode58,demux_guppy_fastq_new/barcode58/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode60,barcode60,demux_guppy_fastq_new/barcode60/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode64,barcode64,demux_guppy_fastq_new/barcode64/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode66,barcode66,demux_guppy_fastq_new/barcode66/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode67,barcode67,demux_guppy_fastq_new/barcode67/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode72,barcode72,demux_guppy_fastq_new/barcode72/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode79,barcode79,demux_guppy_fastq_new/barcode79/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode89,barcode89,demux_guppy_fastq_new/barcode89/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode90,barcode90,demux_guppy_fastq_new/barcode90/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m
barcode96,barcode96,demux_guppy_fastq_new/barcode96/fastq_runid_5363c81269c5ff44cc45e657b79b1135be0297cb_0.fastq,5m

**Comment by vasquini** [comment]
It seems like the demultiplexing error was due to an incorrect barcoding kit being passed to guppy through the config file.
