### ISSUE TITLE
Test Data for Basecalling Not working

### ISSUE THREAD

**Issue by vasquini** [BeatsonLab-MicrobialGenomics/micropipe#7]
So I have been trying to run micropipe. And I always fail in the demultiplexing step with my own data (there is always successful basecalling and guppy is definitely being located as I made appropriate changes in config file). So I decided to run with the example samplesheet and that is failing from the very start. Like there isn't successful basecalling or anything. I get the following error. I tried running this to get a better understanding of a working samplesheet but this is not helpful.
[-        ] process > basecalling_demultiplexing_... -
[-        ] process > pycoqc                         -
[-        ] process > assembly:porechop              -
[-        ] process > assembly:japsa                 -
[-        ] process > assembly:flye                  -
[-        ] process > assembly:racon_cpu             -
[-        ] process > assembly:medaka_cpu            -
[-        ] process > assembly:nextpolish            -
[-        ] process > assembly:fixstart              -
[-        ] process > assembly:quast                 -
[barcode01, S24, 5.5m]
[barcode01, /scicomp/home-pure/suj7/test_data/S24EC_1P_test.fastq.gz, /scicomp/home-pure/suj7/test_data/S24EC_2P_test.fastq.gz]
No such file: /scicomp/home-pure/suj7/false

**Comment by vmurigneu** [comment]
Hi @vasquini 

The test data does not include raw fast5 reads but already basecalled fastq files for one sample. Therefore it can only be used to test the assembly-only workflow.

Can you please share the samplesheet you used and the command to run nextflow

**Comment by vmurigneu** [comment]
Hi @vasquini 
No the test data only contains one sample so it is not for testing the demultiplexing step. Yes I realised the documentation on the test data part is confusing, I will modify, thanks for reporting
